language: node_js
node_js:
  - "10.17.0"

branches:
  only:
  - master
  - development
  - dev2

cache: yarn

before_install:
- export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
- export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
- yarn global add jest now
- cd app && yarn
- cd ..

jobs:
  include:
  - stage: tests
    install:
      - cd app
    script:
      - yarn test
  - stage: deploy-dev
    if: "(NOT env(AUTHOR_NAME) =~ ^Travis AND (NOT type IN (pull_request)) AND (branch= development))"
    script:
      - now alias --scope kauri --token=$NOW_TOKEN $(now -A qa.now.json --scope kauri --token=$NOW_TOKEN) qa.kauri.io
